### ISSUE TITLE
Can I use this to generate text interpolated between a start Sentence and an End Sentence?

### ISSUE THREAD

**Issue by Fredrum** [TIXFeniks/neurips2019_intrus#1]
Hi!
I am looking for a way to generate inbetween text when giving one or more start sentences and also one or more end sentences.
Would your model be able to do this? If so would you be able to advice how I could possibly use your code to try it?

Cheers, Fred

**Comment by TIXFeniks** [comment]
Hello, Fred! 
Thank you for your interest in our paper!
Yes, our model is able to do this. To train and use it that way you would have to make some changes to our code and data preprocessing:
1) Use a custom encoder (or none at all) depending on the details of your task.
2) Pass the whole texts instead of distinct sentences as data.
3) (Optional) Try pretraining our model for generating single sentences (as it would be much faster)
4) (Optional) Modify ```GenerateReferenceInserts``` and ```SampleReferenceInserts``` classes such that they force some starting and ending sentences to be generated first and remove the steps of their generation from the results of ```generate_trajectories``` methods. This way the model will train in the same setup as you plan to use it.
5) follow our usual training procedure: Using the whole texts as decoding target, first pretrain the model with fixed orders and then finetune it with the sampled ones. (this could take a while even with 8 GPUs). 
6) Change [lib/inference.py](https://github.com/TIXFeniks/neurips2019_intrus/blob/master/lib/inference.py) so that it supports passing the prefix of the generation trajectory and allowing inserts only in between the initial starting/ending sentences.
 
While our model is capable of solving your task, it would be slow as our model has worse computational complexity (O(n^3)) compared to the original transformer (O(n^2)), which is especially prominent on long sequences such as the ones in your task. I would suggest trying other approaches before using ours:

1) Simple approach: You need the outputs to be conditioned on some starting/ending sentences. You could just pass them as inputs to the conventional left-to-right models by introducing additional encoders. 
2) Other insertion-based approaches: As of 2019 several insertion-based models have been proposed (see related work in out paper).  in your case I would suggest using  the implementation by Gu et al. (https://arxiv.org/abs/1902.01370 paper, https://github.com/MultiPath/Squirrel -- implementation) as it claims to have better computational complexity (O(n^2)), which would be helpful in your task. There is only one issue -- their method uses Beam Search instead of sampling when generating training insertion trajectories, which we show to be less optimal in terms of resulting quality, but sampling is fairly easy to implement.

**Comment by Fredrum** [comment]
Hi  Dmitriy,

Thank you so much for your substantial reply to my message!
I was very excited to find something that seemed to be matching what I was looking for so I will definitely try to modify your system even if it's computationally not optimal, just to try and get the ball rolling while I learn more about ml nlp.

My interest is more in 'Story Generation' and maybe that's why so far there hasn't been many papers/systems along these lines, as maybe that's not yet a commercially viable direction for this field? I understand that getting software to make stories is incredibly hard but with these newest ideas the last couple of years it seems like you're getting a bit closer.

I'll take a look at the Squirrel too!

Thank you very much!
Fred
